### ISSUE TITLE
egg.js 使用ip2region 报错

### ISSUE THREAD

**Issue by best-fan** [yourtion/node-ip2region#30]
/usr/blog/api/node_modules/ip2region/dist/lib/ipv6.js:199
[egg-scripts]         if (ip6 === 0x1n) {
[egg-scripts]                     ^^^
[egg-scripts] 
[egg-scripts] SyntaxError: Invalid or unexpected token
[egg-scripts]     at createScript (vm.js:80:10)
[egg-scripts]     at Object.runInThisContext (vm.js:139:10)
[egg-scripts]     at Module._compile (module.js:617:28)
[egg-scripts]     at Object.Module._extensions..js (module.js:664:10)
[egg-scripts]     at Module.load (module.js:566:32)
[egg-scripts]     at tryModuleLoad (module.js:506:12)
[egg-scripts]     at Function.Module._load (module.js:498:3)
[egg-scripts]     at Module.require (module.js:597:17)
[egg-scripts]     at require (internal/module.js:11:18)
[egg-scripts]     at Object.<anonymous> (/usr/blog/api/node_modules/ip2region/dist/lib/index.js:7:32)
[egg-scripts] 2021-01-13 11:58:29,357 ERROR 31607 nodejs.AppWorkerDiedError: [master] app_worker#1:31623 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
[egg-scripts]     at Master.onAppExit (/usr/blog/api/node_modules/egg-cluster/lib/master.js:510:21)
[egg-scripts]     at emitOne (events.js:116:13)
[egg-scripts]     at Master.emit (events.js:211:7)
[egg-scripts]     at Messenger.sendToMaster (/usr/blog/api/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
[egg-scripts]     at Messenger.send (/usr/blog/api/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
[egg-scripts]     at EventEmitter.cluster.on (/usr/blog/api/node_modules/egg-cluster/lib/master.js:353:22)
[egg-scripts]     at emitThree (events.js:141:20)
[egg-scripts]     at EventEmitter.emit (events.js:217:7)
[egg-scripts]     at ChildProcess.worker.process.once (internal/cluster/master.js:191:13)
[egg-scripts]     at Object.onceWrapper (events.js:317:30)
[egg-scripts] name: "AppWorkerDiedError"
[egg-scripts] pid: 31607
[egg-scripts] hostname: iz2zeinnzibsruhaliwavbz
[egg-scripts] 
[egg-scripts] 2021-01-13 11:58:29,357 ERROR 31607 [master] app_worker#1:31623 start fail, exiting with code:1
[egg-scripts] 2021-01-13 11:58:29,358 ERROR 31607 [master] exit with code:1
[egg-scripts] 2021-01-13 11:58:29,364 ERROR 31613 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
[egg-scripts] 2021-01-13 11:58:29,367 ERROR 31613 [agent_worker] exit with code:110
[egg-scripts]

**Comment by best-fan** [comment]
node  版本过低导致的  升级成了最新版本正常了
